# Railway Deployment Configuration
# This file tells Railway how to deploy your application

[build]
  command = "npm install --only=production"

[deploy]
  startCommand = "npm start"
  healthcheckPath = "/healthz"
  healthcheckTimeout = 300

[env]
  NODE_ENV = "production"
  PORT = "3000"
